ktor:
  application:
    modules:
      - localrag.ApplicationKt.module
  deployment:
    port: 8080
    requestReadTimeoutSeconds: 300
    responseWriteTimeoutSeconds: 300

app:
  tempFolder: "./.temp"
  llmModel: "qwen3"
  textEmbeddingModel: "mxbai-embed-large"
  ollamaBaseUrl: "http://localhost:11434"
  chunkSize: 7500
  chunkOverlap: 100
  db:
    host: "localhost"
    port: 5432
    name: "embedding_db"
    user: "dev_user"
    password: "dev_password"
    tableName: "documents"
